# docker-compose.yml

version: '3'

services:
  rag-app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ./documents:/documents
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1