# docker-compose.yml

# version: '3'

services:
  rag-app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ./documents:/documents
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - PYTHONUNBUFFERED=1